### ISSUE TITLE
Add Scientific Functions

### ISSUE THREAD

**Issue by Mandipbhattarai** [pccoe-acm-hacktoberfest-2023/GDSC_calculator#3]
Include scientific functions like trigonometry (sine, cosine, tangent), logarithms, exponentials, and square roots.

**Comment by Kinjal2004** [comment]
I want to work on this issue.

**Comment by Girish345** [comment]
I want to work on that can you please assign it to me

**Comment by Ranjitdon** [comment]
Hey Mandip, your project looks interesting and challenging. I would love to contribute to this project.

**Comment by Mandipbhattarai** [comment]
We will not assign the project to anyone!

Just work on it and raise a PR, if found good we will merge it.

**Comment by mr-osiris** [comment]
i have added functionality like sin cos tan log ln square square root and raised pr for it
