### ISSUE TITLE
Integration of Virtual Keyboard with Text Input Box

### ISSUE THREAD

**Issue by Mandipbhattarai** [pccoe-acm-hacktoberfest-2023/GDSC_calculator#4]
To enhance the user experience and accessibility of our calculator website, we aim to integrate a virtual keyboard with the text input box. This integration will allow users to input text using both their physical keyboard and an on-screen virtual keyboard, ensuring flexibility and convenience for a broader audience.

**Comment by Sairajepawar** [comment]
@Mandipbhattarai i have resolved the issue please check the request and merge it if there is no futher issue
